### ISSUE TITLE
Do Mesmerist not have Cantrips?

### ISSUE THREAD

**Issue by Ricahrd1016** [Telyl/WOTRMesmerist#2]
![QQ浏览器截图20240728181206](https://github.com/user-attachments/assets/06c46382-aa4a-4e8e-9afb-d0650ea864b6)

**Comment by Ricahrd1016** [comment]
Do Mesmerist not have Cantrips?

**Comment by Telyl** [comment]
Good find! I think this is because of the way I set up their spell book. They aren't considered divine or arcane so Owlcat handles the gui as though they're an alchemist. You should still have access to them as actual castable spells, though. Unfortunately, I cannot fix this bug.

I did catch a bug with the AreaDismissal missing from their 0th level spells - Fixed.

![image](https://github.com/user-attachments/assets/b9f210c0-f594-4277-af94-055698a84d74)
